name: Test

on: [push]

jobs:
  Test:
    runs-on: [ubuntu-24.04]
    env:
      RUST_VERSION: 1.90.0
      SOLANA_VERSION: 2.2.20
      ANCHOR_VERSION: 0.32.1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libudev-dev llvm libclang-dev protobuf-compiler libssl-dev

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: rustfmt, clippy

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v${{ env.SOLANA_VERSION }}/install)"
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor
        run: cargo install --git https://github.com/coral-xyz/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli

      # - name: Setup Rust & Solana & Anchor
      #   run: |
      #     # Install Solana, Rust, Anchor
      #     # sh -c "$(curl -sSfL https://solana-install.solana.workers.dev)" -- v${SOLANA_VERSION} | bash
      #     curl --proto '=https' --tlsv1.2 -sSfL https://solana-install.solana.workers.dev | bash
      #     # Source the environment to get correct paths
      #     echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      #     echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      #     echo "$HOME/.avm/bin" >> $GITHUB_PATH
      
      - name: Generate Key
        run: solana-keygen new --no-passphrase

      - name: Verify Installed Versions
        run: |
          rustc --version
          cargo --version
          solana --version
          anchor --version

      - name: Build
        run: anchor build

      - name: Install Dependencies
        run: yarn install

      - name: JS E2E Tests
        run: anchor test

      - name: Install llvm-cov
        run: cargo install cargo-llvm-cov
      
      - name: Rust Tests
        run: cargo llvm-cov