name: Test

on: [push]

jobs:
  Test:
    runs-on: [ubuntu-22.04]
    env:
      RUST_VERSION: 1.90.0
      SOLANA_VERSION: 2.2.14
      ANCHOR_VERSION: 0.31.1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true
          components: rustfmt, clippy

      - name: Setup Rust & Solana & Anchor
        run: |
          # Install Solana, Rust, Anchor
          curl --proto '=https' --tlsv1.2 -sSfL https://solana-install.solana.workers.dev | bash
          # Source the environment to get correct paths
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          echo "$HOME/.avm/bin" >> $GITHUB_PATH
      
      - name: Generate Key
        run: solana-keygen new --no-passphrase

      - name: Build
        run: anchor build

      - name: Install Dependencies
        run: yarn install

      - name: JS E2E Tests
        run: anchor test

      - name: Install llvm-cov
        run: cargo install cargo-llvm-cov
      
      - name: Rust Tests
        run: cargo llvm-cov